### ISSUE TITLE
Migrate all components from lux

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lux-styleguidist#122]
The following components still have not been migrated from the lux repo to this repo.  They can be [migrated following these procedures](https://github.com/pulibrary/lux-styleguidist?tab=readme-ov-file#copying-vue-2-components-from-lux).

- [x] Banner
- [x] InputCheckbox
- ~~[ ] InputDataList~~ (This component has never been used. LuxSelect2 is the preferred implementation.)
- [x] InputRadio
- [x] Loader
- [x] LuxSelect2 (We think this in DSS)
- [x] LuxIconArrowDown
- [x] LuxIconArrowRight
- [x] LuxIconConsulting
- [x] LuxIconDelivery
- [x] LuxIconDerivativesHealthy
- [x] LuxIconDerivativesUnhealthy
- [x] LuxIconEdit
- [x] LuxIconExclamation
- [x] LuxIconFileHealthy
- [x] LuxIconFileUnhealthy
- [x] LuxIconFilter
- [x] LuxIconFlower
- [x] LuxIconHospital
- [x] LuxIconInfo
- [x] LuxIconLockClose
- [x] LuxIconLockOpen
- [x] LuxIconNote
- [x] LuxIconPerson
- [x] LuxIconPicture
- [x] LuxIconQuestion
- [x] LuxIconQuestionFilled
- [x] LuxIconRelax
- [x] LuxIconReportHealthy
- [x] LuxIconReportRemove
- [x] LuxIconReportUnhealthy
- [x] LuxIconResearch
- [x] LuxIconScales
- [x] LuxIconUserHome
- [x] LuxIconVacation
- [x] LuxIconView
- [x] LogoFacebook
- [x] LogoFriends
- [x] LogoGovDocs
- [x] [LogoTwitter (should probably display an updated icon)](https://approvals-staging.princeton.edu/my_requests)
- [x] LogoUniversity
- [x] LibraryFooter
- ~~[ ] LoginForm~~ Example only, no need to. move
- ~~[ ] SpecialCollectionsFooter~~ Don't believe it's used by any apps

**Comment by sdellis** [comment]
The component migration EPIC is DONE! 🎉
