### ISSUE TITLE
Library Logo Icon Does Not Display in Styleguide

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lux-styleguidist#159]
The logo graphic doesn't render https://pulibrary.github.io/lux-styleguidist/#/Components?id=luxlibrarylogo. Also verified this happens in our local environment running the main branch. It does seem to work fine using the reference lux Alpha releases in the approvals-staging environment.

**Comment by christinach** [comment]
resolved by https://github.com/pulibrary/lux-styleguidist/pull/161
