### ISSUE TITLE
can't import dist/system/tokens/tokens.scss

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/lux-styleguidist#181]
[plugin:vite:import-analysis] Missing "./dist/system/tokens/tokens.scss" specifier in "lux-design-system" package

I'm not sure whether this should be made to work or whether it should be removed from https://github.com/pulibrary/lux-styleguidist/blob/main/UpgradeInstructions.md

**Comment by hackartisan** [comment]
@eliotjordan pointed out there's no such file in this repo.

**Comment by eliotjordan** [comment]
Closed by https://github.com/pulibrary/lux-styleguidist/pull/184
