### ISSUE TITLE
Compare what components are in approvals vs what is in styleguidist

### ISSUE THREAD

**Issue by christinach** [pulibrary/lux-styleguidist#40]
Write separate ticket for each component that is used in [approvals-approvals](https://github.com/pulibrary/approvals/tree/main/app/javascript/components) and [approvals-views](https://github.com/pulibrary/approvals/tree/main/app/views) but is not yet exist in lux-styleguidist.

**Comment by sandbergja** [comment]
Tickets opened in the lux-styleguidist repo
